"""Add rover and obstacle datamodels

Revision ID: 0edb9f109a04
Revises:
Create Date: 2025-07-28 16:46:34.028405

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0edb9f109a04"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "obstacle",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "rover",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column(
            "direction", sa.Enum("N", "E", "S", "W", name="direction"), nullable=False
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rover")
    op.drop_table("obstacle")
    # ### end Alembic commands ###
